version: "3.8"
services:
  mysql-db:
    image: 'mysql:8.0'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
    ports:
      - ${MYSQL_PORT_MAP}
#    volumes:
#      - mysql-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 20
  backend:
    build: backend
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - ${BACKEND_PORT_MAP}
    environment:
      spring.datasource.driver-class-name: 'com.mysql.cj.jdbc.Driver'
      spring.datasource.url: 'jdbc:mysql://${DATABASE_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}'
      spring.datasource.username: ${MYSQL_USER}
      spring.datasource.password: ${MYSQL_PASSWORD}
      spring.liquibase.url: 'jdbc:mysql://${DATABASE_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}'
      spring.liquibase.user: ${LIQUIBASE_USER}
      spring.liquibase.password: ${LIQUIBASE_PASSWORD}
      server.port: ${BACKEND_PORT}
      spring.security.user.name: ${ADMIN_USERNAME}
      spring.security.user.password: ${ADMIN_PASSWORD}
      jwtSecret: ${JWT_SECRET}
      jwtExpirationMs: ${JWT_EXPIRATION_MS}
      jwtCookieName: ${JWT_COOKIE_NAME}
  frontend:
    build: frontend
    depends_on:
      - backend
    ports:
      - ${FRONTEND_PORT_MAP}
#volumes:
#  mysql-db: